### ISSUE TITLE
LSP and code navigation is very slow when working with C source codes with many lines

### ISSUE THREAD

**Issue by pidgeon777** [abzcoding/lvim#21] opened 2022-03-08 14:12 UTC
When I try to edit a C source file, if it is made of thousands of lines, then code navigation and LSP autocomplete is extremely slow.

What I noticed is that, if I do this to the buffer:

```vim
:set filetype=txt
:set syntax=c
```

then the LSP remains active with autocomplete, diagnostics etc. plus basic syntax highlight, but everything is much faster.

Probably this is due to some plugin or autocommand which supposedly get activated when I open a C file, with subsequent `clangd` LSP server launch.

Question is, how could I exactly identify the components slowing down everything, eventually disabling them, without having every time to repeat the two commands described above?

Some notes:

- Disabling the LSP `clangd`, still leads to code editing slowness.
- `TSBufDisable highlight & indent` seems to improve speed.
- `IndentBlanklineDisable` also improve speed.

**Comment by abzcoding** [comment] 2022-03-08 15:50
It might come from this plugin -> https://github.com/abzcoding/lvim/blob/ce0e9b37e25b8f3fd61bac9135a3ff4da26bc4ca/lua/user/plugins.lua#L546-L550

please disable that and also remove `clangd` from this part https://github.com/abzcoding/lvim/blob/ce0e9b37e25b8f3fd61bac9135a3ff4da26bc4ca/config.lua#L94-L99

and check if that helps speed things up, 
otherwise, i'm not sure why would `indentblankline` or `highlight` and `indent` slow you down
but you can do these ( inside `lua/user/builtin.lua` )
```lua
lvim.builtin.treesitter.indent = { enable = true, disable = { "yaml", "python", "c" } }
lvim.builtin.treesitter.highlight.disable = { "org", "c" }
```

**Comment by abzcoding** [comment] 2022-03-08 16:49
make sure to run a `:LvimCacheReset` after doing those changes

**Comment by pidgeon777** [comment] 2022-03-08 17:01
Ok, will try that.

In the meanwhile, even if `clangd` is now disabled, the slowness still persists, unless I execute the two `set` commands above.

Probably the cause is something else.

The one to be extremely slow, is **insert mode**.

Also I tried this:

```vim
TSBufDisable highlight
TSBufDisable indent
```
but it didn't improve things, just a bit in visual mode line/words navigation.

I think it would be the same of your suggestion:

```lua
lvim.builtin.treesitter.indent = { enable = true, disable = { "yaml", "python", "c" } }
lvim.builtin.treesitter.highlight.disable = { "org", "c" }
```

**Comment by abzcoding** [comment] 2022-03-08 17:04
well i'm not sure what else to say, i can't reproduce this on my system, this is my neovim version
<img width="310" alt="Screen Shot 2022-03-08 at 8 34 24 PM" src="https://user-images.githubusercontent.com/10992695/157288380-9fa9dcfc-88da-4888-8337-f27d465b2ed4.png">

**Comment by abzcoding** [comment] 2022-03-08 17:25
what happens when you run `:LspInstallInfo` ? does it show `clangd` as installed?

**Comment by pidgeon777** [comment] 2022-03-08 18:45
Output of `LspInstallInfo`:

![image](https://user-images.githubusercontent.com/13739892/157302296-189a4c9a-993b-4f39-b3a3-115f0bad9c7e.png)

I tried to do something simpler. I did all of the new tests with LSP disabled.

The fact is that the issue still occurs. Extremely slow in insert mode when opening large files (tested only with C sources).

I did this, all with no LSP:

1. Open large C file.
2. Do some quick random edits in insert mode -> extremely laggy.
3. Disable all of the TreeSitter features for that buffer -> light improvement, still laggy.
4. `:IndentBlanklineDisable` -> light improvement, still laggy.
5. `:Gitsigns detach_all` -> no noticeable improvements.
6. `:set filetype=txt`
7. `:set syntax=c`
8. Did some random quick edits, and it was way faster.

So, LSP is definitely not the cause.

My OS is Windows 10 Pro.

**Comment by abzcoding** [comment] 2022-03-08 18:49
sadly i only have mac and linux environments, but i'm note sure what is causing your config to be this slow
i would suggest trying https://github.com/LunarVim/LunarVim/pull/2330

and also using a simpler lunarvim config and just pick and choose what you like from my config, 
since i've not tested my config on windows, i'm not sure what else to add, hope you can find a proper solution to this

i'm closing this issue, since i'm not gonna work on it

**Closed by abzcoding** 2022-03-08 18:49 UTC
Labels: bug

**Comment by pidgeon777** [comment] 2022-03-08 18:53
I will be happy to investigate my issue, could you please provide me any hint?

**Comment by abzcoding** [comment] 2022-03-08 19:08
> I will be happy to investigate my issue, could you please provide me any hint?

couple of notes:
1. check if changing your terminal/ environment changes anything
2. check `:autocmd` to see which autocommands has run, and see if disabling them would help with anything
3. disable `treesitter indent and hightlight`
```lua
lvim.builtin.treesitter.indent.enable = false
lvim.builtin.treesitter.highlight.enable = false
```
4. try disabling `tabnine`, `copilot` and `lsp_signature`
```lua
lvim.builtin.sell_your_soul_to_devil = false
lvim.builtin.tabnine = { active = false }
-- comment this part in `lua/user/plugins.lua`
--    {
--      "ray-x/lsp_signature.nvim",
--      config = function()
--        require("user/lsp_signature").config()
--      end,
--      event = { "BufRead", "BufNew" },
--    },

```
5. if nothing else worked, look into this
https://github.com/abzcoding/lvim/blob/45698c70b5e9de01308a754ff8ec853b614460ab/lua/user/autocommands.lua#L16-L30
and maybe using 
```vim
augroup ShowLineNumberForLongFiles
  autocmd!
  autocmd BufEnter * if line('$') > 1024 | set filetype=txt | endif
augroup END
```

tbh, i'm not sure 🤷
