### ISSUE TITLE
Neotest run all issue

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#96] opened 2022-10-27 12:45 UTC
Hello,
I took the configuration for `neotest` from your repository (thanks for it!!!).

I am having some issue with this function

https://github.com/abzcoding/lvim/blob/7695615ccb39cf60a8e656d3463d162e0344b351/lua/user/ntest.lua#L91-L96

It is always returning 

```
Error  01:43:00 PM msg_show.lua_error E5108: Error executing lua ...config/lvim/lua/user/ntest.lua:90: attempt to call field 'adapters' (a nil value)
stack traceback:
	...config/lvim/lua/user/ntest.lua:90: in function 'run_all'
	[string ":lua"]:1: in main chunk
```

I am wondering if the same happens to you or it is something related to config..

**Comment by abzcoding** [comment] 2022-10-27 13:31
that is a bit weird, i just ran it in a rust `lib.rs` file and I have no issues
<img width="1920" alt="Screenshot 2022-10-27 at 4 59 31 PM (2)" src="https://user-images.githubusercontent.com/10992695/198297928-1a690b44-8669-4e06-b37d-e653923dd8ad.png">


maybe you can change this line
```lua
local neotest = require "neotest"
```
to 
```lua
  local found, neotest = pcall(require, "neotest")
  if not found then
    vim.notify("neotest is not loaded yet", vim.log.levels.ERROR)
    return
  end
```

if see if the issue is the lazy loading of neotest

**Comment by crisidev** [comment] 2022-10-27 14:48
Thanks for double checking. It's probably something in my configuration as `neotest.run` exist, but the `adapters()` method is never attached to the struct:

```
print(vim.inspect(require("neotest").run))
{
  rerun_task_group = <function 1>,
  run = <function 2>,
  run_last = <function 3>,
  <metatable> = {
    __call = <function 4>
  }
}
```

**Comment by crisidev** [comment] 2022-10-27 15:22
I have tracked it down to the integration with "overseer". If I disable it, `adapters()` works as expected.

**Comment by abzcoding** [comment] 2022-10-27 16:18
should be fixed via https://github.com/abzcoding/lvim/commit/0791beb618a33254a2d3ae2d2aec3d649781f6d5

**Closed by abzcoding** 2022-10-27 16:18 UTC

**Comment by crisidev** [comment] 2022-10-28 11:12
Nice! Thanks a lot.
