### ISSUE TITLE
Will not detect local eslint configuration

### ISSUE THREAD

**Issue by radugaf** [abzcoding/lvim#83] opened 2022-09-09 08:19 UTC
I've been using your configuration for quite some time now (super awesome btw!!). I just did a `git pull` a few minutes ago and it seems like everything node related just broke. 

The issues:
(1) Formatting will timeout
(2) Does not see the local eslint and prettier files

Please let me know what info would you need from my side. Trying to help but I'm pretty new at this.

**Comment by abzcoding** [comment] 2022-09-09 08:21
thanks, mate, ok first off, can you pinpoint which commit causes these issues for you?

**Comment by radugaf** [comment] 2022-09-09 08:37
I was just checking every commit from the past month from both your repo and from [Lunarvim](https://github.com/LunarVim/LunarVim/pulls?q=is%3Apr+is%3Aclosed). I am not really sure what change caused it to break.

What is even stranger is that you haven't updated the null-ls configuration, or anything related to `eslint` (for example), and neither on the main repo. So I can only assume is a bug somewhere (or a breaking change) in the plugins.

**Comment by abzcoding** [comment] 2022-09-09 08:38
that is a bit strange tbh,
can you try this?

```sh
# run the following only once to fix the issue
find ~/.local/share/lunarvim/site/pack/packer -maxdepth 2 -mindepth 2 -type d -exec git -C {} checkout main \;
find ~/.local/share/lunarvim/site/pack/packer -maxdepth 2 -mindepth 2 -type d -exec git -C {} checkout master \;

# this will keep lunarvim up to date
git -C ~/.local/share/lunarvim/lvim pull

# use this command to keep the plugins up to date
find ~/.local/share/lunarvim/site/pack/packer -maxdepth 2 -mindepth 2 -type d -exec git -C {} pull \;
```

**Comment by radugaf** [comment] 2022-09-09 09:10
Ran the commands but they did nothing...  :-( Any other suggestions?

**Comment by abzcoding** [comment] 2022-09-09 09:14
> Ran the commands but they did nothing... :-( Any other suggestions?

check `~/.cache/nvim/lvim.log` and `~/.cache/nvim/lsp.log` and `~/.cache/nvim/log` 
those might be helpful

**Comment by abzcoding** [comment] 2022-09-09 17:53
@radugaf can you remove these lines and see if everything gets fixed?

https://github.com/abzcoding/lvim/blob/0bc4fde98cf5f6f966b60ad4946936b7bc7d4b1a/lua/user/neovim.lua#L49-L50

**Comment by radugaf** [comment] 2022-09-12 10:30
@abzcoding  tried it, still does not work .. I will keep trying things until I will figure it out. Will post here updates as soon as I have any

**Comment by abzcoding** [comment] 2022-10-23 06:30
sadly i can't reproduce this issue no matter what I do, so I'll close this

**Closed by abzcoding** 2022-10-23 06:30 UTC
Labels: invalid
